# Generated by Django 5.0.6 on 2024-06-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemInfo',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
